name: o_connect
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.2+20

environment:
  sdk: ">=2.19.4 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # Package used for state management
  provider: ^6.0.5
  # Package used for Rest Api calling
  dio:
  # Packages used for local db with secure storage
  hive: 2.2.3
  flutter_secure_storage: ^8.0.0
  # Package used for accessing file paths of device
  path_provider: ^2.0.15
  # Package used for logging data or message
  logger: ^1.4.0
  # Package used for checking internet connection
  connectivity_plus: ^5.0.1
  # Package used for managing screen sizes
  flutter_screenutil:
  device_info_plus: ^9.0.2
  dropdown_button2:
  flutter_svg:
  #Package used for whiteboard
  #  flutter_drawing_board:
  #    path: packages/flutter_drawing_board-master
  image_picker: ^1.0.0
  url_launcher: ^6.1.11
  flutter_colorpicker: ^1.0.3
  percent_indicator:
  screenshot: ^2.1.0
  flutter_html_to_pdf:
  file_picker: ^6.1.1
  open_file: any
  lottie: ^2.4.0
  just_audio: ^0.9.34
  image_gallery_saver:
  marquee: ^2.2.3
  emoji_picker_flutter:
  flutter_webrtc: ^0.9.47
  flutter_background: ^1.2.0
  image_cropper: ^5.0.0
  another_flushbar: ^1.12.30
  youtube_player_flutter: ^8.1.2
  video_player: ^2.7.0
  video_thumbnail: ^0.5.3
  get_it: ^7.6.0
  shared_preferences: ^2.2.0
  encrypt: ^5.0.1
  device_preview: ^1.1.0
  #  flutter_pdfview: ^1.3.1
  uuid: ^3.0.6
  ed_screen_recorder:
  retrofit: ^4.0.1
  permission_handler: ^11.0.1
  syncfusion_flutter_charts: ^22.2.12
  phosphor_flutter: ^1.4.0
  #  pdfx: ^2.4.0
  pdf: ^3.10.4
  json_annotation: ^4.8.1
  fl_pip: ^2.0.0
  fl_chart: ^0.67.0
  intl:
  syncfusion_flutter_datepicker:
  dartz: ^0.10.1
  http_parser: ^4.0.2
  socket_io_client: ^2.0.3+1
  equatable: ^2.0.5
  mediasoup_client_flutter:
    path: packages/mediasoup_client_flutter-0.8.5
  shimmer: ^3.0.0
  chewie: ^1.7.1
  dotted_border: ^2.1.0
  flutter_hsvcolor_picker: ^1.2.3
  firebase_dynamic_links: ^5.4.2
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  flutter_foreground_task: ^6.1.2
  math_expressions: ^2.4.0
  flutter_inappwebview: ^5.8.0
  speech_to_text: ^6.4.1
  share_plus: ^7.2.2
  flutter_isolate: ^2.0.4
  mime: ^1.0.4
  flip_board: ^1.0.0
  html_editor_enhanced:
    path: packages/html-editor-enhanced
  oes_chatbot:
    path: packages/o-chat-app/
  otp_input_editor: ^0.0.8
  wakelock_plus: ^1.1.4
  replay_kit_launcher: ^1.0.0
  buttons_tabbar: ^1.3.8
  camera: ^0.10.5+9
  external_app_launcher: ^4.0.0
  fluttertoast: ^8.2.4
  internet_connection_checker: ^1.0.0+1
  simple_gradient_text: ^1.3.0
  flutter_session_jwt:
  flutter_cache_manager: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator:
  build_runner: ">=2.3.0 <4.0.0"
  json_serializable: ^6.7.1

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/new_ui_icons/
    - assets/new_ui_icons/introslider/
    - assets/new_ui_icons/dashboard/
    - assets/new_ui_icons/library/
    - assets/new_ui_icons/library/sheet/
    - assets/new_ui_icons/appbar/
    - assets/new_ui_icons/profile/
    - assets/new_ui_icons/events/
    - assets/new_ui_icons/webinar_dashboard/
    - assets/new_ui_icons/home_screen/
    - assets/new_ui_icons/chat_icons/
    - assets/new_ui_icons/all_participants_icons/
    - assets/new_ui_icons/poll/
    - assets/new_ui_icons/resound/
    - assets/new_ui_icons/bgm/
    - assets/chat_icons/
    - assets/introslider/
    - assets/pdf/
    - assets/icons/drawer/
    - assets/appbar/
    - assets/images/
    - assets/meeting_history/
    - assets/template/
    - assets/audio/
    - assets/ticker/
    - assets/webninar_bottom_bar_icons/
    - assets/poll/
    - assets/auth/
    - assets/loading_json/
    - assets/whiteboard_icons/
    - assets/whiteboard_icons/new/
    - assets/contacts/
    - assets/contacts_json/
    - assets/chatbot/
    - assets/whiteboard_webview/
    - assets/emoji/
    - assets/webinar/recording/
    - assets/webinar/global/
    - assets/privacy_policy.pdf
    - assets/new_ui_icons/contacts_icons/
    - assets/new_ui_icons/more_icons/
    - assets/new_ui_icons/json_files/
    - shorebird.yaml

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
