// To parse this JSON data, do
//
//     final invitedMeetings = invitedMeetingsFromJson(jsonString);

import 'dart:convert';

List<InvitedMeetings> invitedMeetingsFromJson(String str) => List<InvitedMeetings>.from(json.decode(str).map((x) => InvitedMeetings.fromJson(x)));

String invitedMeetingsToJson(List<InvitedMeetings> data) => json.encode(List<dynamic>.from(data.map((x) => x.toJson())));

class InvitedMeetings {
  String? id;
  String? meetingName;
  DateTime? meetingDate;
  DateTime? endDate;
  DateTime? createdOn;
  DateTime? updatedOn;
  String? duration;
  int? isStarted;
  String? meetingPassword;
  String? participantKey;
  String? username;
  String? autoGeneratedId;
  List<InvitedDetail>? invitedDetails;
  int? isInvitationAccepted;

  InvitedMeetings({
    this.id,
    this.meetingName,
    this.meetingDate,
    this.endDate,
    this.createdOn,
    this.updatedOn,
    this.duration,
    this.isStarted,
    this.meetingPassword,
    this.participantKey,
    this.username,
    this.autoGeneratedId,
    this.invitedDetails,
    this.isInvitationAccepted,
  });

  InvitedMeetings copyWith({
    String? id,
    String? meetingName,
    DateTime? meetingDate,
    DateTime? endDate,
    DateTime? createdOn,
    DateTime? updatedOn,
    String? duration,
    int? isStarted,
    String? meetingPassword,
    String? participantKey,
    String? username,
    String? autoGeneratedId,
    List<InvitedDetail>? invitedDetails,
    int? isInvitationAccepted,
  }) =>
      InvitedMeetings(
        id: id ?? this.id,
        meetingName: meetingName ?? this.meetingName,
        meetingDate: meetingDate ?? this.meetingDate,
        endDate: endDate ?? this.endDate,
        createdOn: createdOn ?? this.createdOn,
        updatedOn: updatedOn ?? this.updatedOn,
        duration: duration ?? this.duration,
        isStarted: isStarted ?? this.isStarted,
        meetingPassword: meetingPassword ?? this.meetingPassword,
        participantKey: participantKey ?? this.participantKey,
        username: username ?? this.username,
        autoGeneratedId: autoGeneratedId ?? this.autoGeneratedId,
        invitedDetails: invitedDetails ?? this.invitedDetails,
        isInvitationAccepted: isInvitationAccepted ?? this.isInvitationAccepted,
      );

  factory InvitedMeetings.fromJson(Map<String, dynamic> json) => InvitedMeetings(
    id: json["_id"],
    meetingName: json["meeting_name"],
    meetingDate: json["meeting_date"] == null ? null : DateTime.parse(json["meeting_date"]),
    endDate: json["end_date"] == null ? null : DateTime.parse(json["end_date"]),
    createdOn: json["created_on"] == null ? null : DateTime.parse(json["created_on"]),
    updatedOn: json["updated_on"] == null ? null : DateTime.parse(json["updated_on"]),
    duration: json["duration"],
    isStarted: json["is_started"],
    meetingPassword: json["meeting_password"],
    participantKey: json["participant_key"],
    username: json["username"],
    autoGeneratedId: json["auto_generated_id"],
    invitedDetails: json["InvitedDetails"] == null ? [] : List<InvitedDetail>.from(json["InvitedDetails"]!.map((x) => InvitedDetail.fromJson(x))),
    isInvitationAccepted: json["is_invitation_accepted"],
  );

  Map<String, dynamic> toJson() => {
    "_id": id,
    "meeting_name": meetingName,
    "meeting_date": meetingDate?.toIso8601String(),
    "end_date": endDate?.toIso8601String(),
    "created_on": createdOn?.toIso8601String(),
    "updated_on": updatedOn?.toIso8601String(),
    "duration": duration,
    "is_started": isStarted,
    "meeting_password": meetingPassword,
    "participant_key": participantKey,
    "username": username,
    "auto_generated_id": autoGeneratedId,
    "InvitedDetails": invitedDetails == null ? [] : List<dynamic>.from(invitedDetails!.map((x) => x.toJson())),
    "is_invitation_accepted": isInvitationAccepted,
  };
}

class InvitedDetail {
  String? omailEmailId;
  String? email;
  int? contactId;
  String? name;
  int? contactFlag;
  int? roleId;
  String? profilePic;
  String? firstName;
  String? lastName;
  bool? isNotified;
  int? isInviteAccepted;

  InvitedDetail({
    this.omailEmailId,
    this.email,
    this.contactId,
    this.name,
    this.contactFlag,
    this.roleId,
    this.profilePic,
    this.firstName,
    this.lastName,
    this.isNotified,
    this.isInviteAccepted,
  });

  InvitedDetail copyWith({
    String? omailEmailId,
    String? email,
    int? contactId,
    String? name,
    int? contactFlag,
    int? roleId,
    String? profilePic,
    String? firstName,
    String? lastName,
    bool? isNotified,
    int? isInviteAccepted,
  }) =>
      InvitedDetail(
        omailEmailId: omailEmailId ?? this.omailEmailId,
        email: email ?? this.email,
        contactId: contactId ?? this.contactId,
        name: name ?? this.name,
        contactFlag: contactFlag ?? this.contactFlag,
        roleId: roleId ?? this.roleId,
        profilePic: profilePic ?? this.profilePic,
        firstName: firstName ?? this.firstName,
        lastName: lastName ?? this.lastName,
        isNotified: isNotified ?? this.isNotified,
        isInviteAccepted: isInviteAccepted ?? this.isInviteAccepted,
      );

  factory InvitedDetail.fromJson(Map<String, dynamic> json) => InvitedDetail(
    omailEmailId: json["omailEmailId"],
    email: json["email"],
    contactId: json["contact_id"],
    name: json["name"],
    contactFlag: json["contact_flag"],
    roleId: json["role_id"],
    profilePic: json["profile_pic"],
    firstName: json["firstName"],
    lastName: json["lastName"],
    isNotified: json["is_notified"],
    isInviteAccepted: json["is_invite_accepted"],
  );

  Map<String, dynamic> toJson() => {
    "omailEmailId": omailEmailId,
    "email": email,
    "contact_id": contactId,
    "name": name,
    "contact_flag": contactFlag,
    "role_id": roleId,
    "profile_pic": profilePic,
    "firstName": firstName,
    "lastName": lastName,
    "is_notified": isNotified,
    "is_invite_accepted": isInviteAccepted,
  };
}
